/**
  * @file    system_cs32f0xx.c
  * @brief   CMSIS Cortex-M0 Device Peripheral Access Layer System Source File.
  *          It contains the system clock configuration for CSA37F7x devices, and is 
  *          generated by the clock configuration .
  * 1.  The file provides two functions and one global variable to be called from user application: 
  *        SystemInit(): Setups the system clock (System clock source, PLL Multiplier and Divider  
  *                 factors,  AHB/APBx prescalers and Flash settings).It is called at startup just after                    
  *                reset and before branch to main program(in "startup_csa37f7x.S" file).
  *        SystemCoreClock variable: Contains the core clock (HCLK), it can be used by the user 
  *                             application to setup the SysTick timer or configure other parameters.
  *        SystemCoreClockUpdate(): Updates the variable SystemCoreClock and must be called 
  *                              whenever the core clock is changed  during program execution.
  * 2. After each device reset the HRC (8 MHz Range) is used as system clock source.
  *    Then SystemInit() function is called, in "startup_csa37f7x.s" file, to configure the 
  *    system clock before to branch to main program.
  * 3. When the system clock source selected by user fails to startup, the SystemInit()
  *    function will do nothing and HRC still used as system clock source. User can 
  *    add some code to deal with this issue inside the SetSysClock() function.
  * 4. The default value of HXT crystal is set to 8MHz, refer to "HXT_VALUE" define
  *    in "cs32f0xx.h" file. When HXT is used as system clock source, directly or
  *    through PLL, and you are using different crystal you have to adapt the HXT
  *    value to your own configuration.
  *
  * 5.The system clock Configuration as follows:
  *-----------------------------------------------------------------------------
  *        System Clock source        | PLL(HRC)
  *-----------------------------------------------------------------------------
  *        SYSCLK                     | 48000000 Hz
  *-----------------------------------------------------------------------------
  *        HCLK                       | 48000000 Hz
  *-----------------------------------------------------------------------------
  *        AHB Prescaler              | 1
  *-----------------------------------------------------------------------------
  *        APB1 Prescaler             | 1
  *-----------------------------------------------------------------------------
  *        APB2 Prescaler             | 1
  *-----------------------------------------------------------------------------
  *        HRC Frequency              | 8000000 Hz
  *-----------------------------------------------------------------------------
  *        PLL MUL                    | 12
  *-----------------------------------------------------------------------------
  *        VDD                        | 3.3 V
  *-----------------------------------------------------------------------------
  *       FMC wait conuter            | 1 
  *-----------------------------------------------------------------------------
  * @author  ChipSea MCU Group
  * @version V1.0.0
  * @date   2018.11.01         
  * @copyright CHIPSEA TECHNOLOGIES (SHENZHEN) CORP.
  * @note 
  * <h2><center>&copy; COPYRIGHT 2018 ChipSea</center></h2>
  *
  */

#include "csa37f7x.h"

/** @addtogroup CMSIS
  * @{
  */

/** @addtogroup csa37f7x_system
  * @{
  */  
  

uint32_t SystemCoreClock    = 48000000;
static __I uint8_t AHBPrescTable[16] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9};


static void SetSysClock(void);


/**
  * @fn void SystemInit (void)
  * @brief  Setup the microcontroller system. Initialize the Embedded Flash Interface,
  *        the PLL and update the SystemCoreClock variable.     
  * @param  None
  * @return None
  */
void SystemInit (void)
{  
	/* Disable reg write protection */
    GCR->REGWRPROT = 0x59;          
    GCR->REGWRPROT = 0x16;
    GCR->REGWRPROT = 0x88;

#ifdef CSA37F70					
	RCC->CLKCON &= ~RCC_CLKCON_PLL_EN;

	/* Reset PLL_CLK_S bit */
	RCC->CLKCON &= ~RCC_CLKCON_PLL_CLK_S;
	
	/* Reset SYSCLK_S bit */
	RCC->CLKSEL0 &= ~RCC_CLKSEL0_SYSCLK_S;

	/* Reset ADC_S, TK_S, UART_S bits */
	RCC->CLKSEL1 &= ~(RCC_CLKSEL1_ADC_S | RCC_CLKSEL1_TK_S | RCC_CLKSEL1_UART_S);
	
    /* Reset TK_OSC_EN bit */
    RCC->CLKCON &= ~RCC_CLKCON_TK_OSC_EN;	
	
    /* Disable all interrupts */
    RCC->CLKCON &= ~(RCC_CLKCON_PLL_LOCK_IE | RCC_CLKCON_PLL_UNLOCK_IE);
#endif

	/* Reset TIM1_S bit */
	RCC->CLKSEL1 &= ~RCC_CLKSEL1_TIM1_S;

    /* Reset HRC14 bit */
    RCC->CLKCON &= ~RCC_CLKCON_HIRC_ADC_EN;

    /* Configure the System clock frequency, AHB/APBx prescalers and Flash settings */
    SetSysClock();	

	/* Enable reg write protection */
    GCR->REGWRPROT = 0x00;
}

/**
  * @fn void SystemCoreClockUpdate (void)
  * @brief  Update SystemCoreClock according to Clock Register Values
  *         The SystemCoreClock variable contains the core clock (HCLK), it can
  *         be used by the user application to setup the SysTick timer or configure
  *         other parameters.
  * @param  None
  * @return None
  */
void SystemCoreClockUpdate (void)
{
    uint32_t temp = 0;

#ifdef CSA37F70
	if((RCC->CLKSEL0 & RCC_CLKSEL0_SYSCLK_S) != (uint32_t)RESET)
	{
  		if ((RCC->CLKCON & RCC_CLKCON_PLL_CLK_S) != (uint32_t)RESET)
   		{
       		/* PLL output select 48MHz */
      		SystemCoreClock = 48000000;
    	}
     	else
      	{
      		/* PLL output select 24MHz */
       		SystemCoreClock = 24000000; 
     	}			
	}	
	else
	{
		SystemCoreClock = HRC_VALUE;	
	}
#else
	SystemCoreClock = HRC_VALUE;
#endif

    /* Get HCLK prescaler */
    temp = AHBPrescTable[(RCC->CLKDIV & RCC_CLKDIV_HCLK_PRE)];

    /* HCLK clock frequency */
    SystemCoreClock >>= temp; 
}

/**
  * @fn static void SetSysClock(void)
  * @brief  Configures the System clock frequency, AHB/APBx prescalers  
  *            and Flash settings. 
  * @param  None
  * @return None
  */
static void SetSysClock(void)
{
	/* Disable reg write protection */
    GCR->REGWRPROT = 0x59;          
    GCR->REGWRPROT = 0x16;
    GCR->REGWRPROT = 0x88;

#ifdef CSA37F70
    /* Set Flash Latency to 1 for 48MHz*/
 	RCC->CLKCON |= RCC_CLKCON_LATENCY;

    /* PLL configuration = 48 MHz */
    RCC->CLKCON |= RCC_CLKCON_PLL_CLK_S;
            
    /* Enable PLL */
    RCC->CLKCON |= RCC_CLKCON_PLL_EN;

    /* Wait till PLL is ready */
    while((RCC->CLKSTATUS & RCC_CLKSTATUS_PLL_STB) == (uint32_t)RESET)
    {
    }	

    /* Select PLL as system clock source */
	RCC->CLKSEL0 |= RCC_CLKSEL0_SYSCLK_S;

    /* Wait till PLL is used as system clock source */
    while ((RCC->CLKSTATUS & RCC_CLKSTATUS_CLK_SW_FAIL) != (uint32_t)RESET)
    {
    }
	
#endif

    /* PCLK = HCLK = SYSCLK */
	RCC->CLKDIV = (uint32_t)0x00000000; 

	/* Enable reg write protection */
    GCR->REGWRPROT = 0x00;
}


/**
  * @}
  */

/**
  * @}
  */

